# Generated by Django 5.0.3 on 2024-03-19 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloq_app', '0004_alter_units_model_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='units_model',
            name='unit',
            field=models.CharField(choices=[('mm', 'Millimeter'), ('inch', 'Inch'), ('m', 'Meter'), ('ft', 'Foot'), ('cm', 'Centimeter')], max_length=10),
        ),
    ]
