# Generated by Django 5.0.3 on 2024-03-26 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloq_app', '0005_alter_units_model_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block_model',
            name='layer',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
