# Generated by Django 5.0.3 on 2024-03-26 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloq_app', '0006_alter_block_model_layer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block_model',
            name='layer',
            field=models.CharField(max_length=100),
        ),
    ]
